Fix quotes of <main>
This changed since 3.4.0-preview1.

```
% docker run --platform linux/amd64 --rm -it ghcr.io/ruby/all-ruby env LANG=C.UTF-8 ALL_RUBY_SINCE=ruby-3.3 ./all-ruby -e 'def foo; time; end; foo'
ruby-3.3.0          -e:1:in `foo': undefined local variable or method `time' for main (NameError)

                    def foo; time; end; foo
                             ^^^^
                        from -e:1:in `<main>'
                exit 1
...
ruby-3.3.4          -e:1:in `foo': undefined local variable or method `time' for main (NameError)

                    def foo; time; end; foo
                             ^^^^
                        from -e:1:in `<main>'
                exit 1
ruby-3.4.0-preview1 -e:1:in 'Object#foo': undefined local variable or method 'time' for main (NameError)

                    def foo; time; end; foo
                             ^^^^
                        from -e:1:in '<main>'
                exit 1
```